import { useQuery } from "@tanstack/react-query";
import { useLocalSearchParams } from "expo-router";
import { Image, ScrollView, StyleSheet, Text, View } from "react-native";
import { useTranslation } from "react-i18next";
import { api } from "../../src/api";
import { ProductCard } from "../../src/components/ProductCard";
import { Chip, ScreenTitle, StateView } from "../../src/components/ui";
import { colors, radius } from "../../src/theme";
export default function FarmerDetail() { const { slug } = useLocalSearchParams<{ slug: string }>(); const { t } = useTranslation(); const farmer = useQuery({ queryKey: ["farmer", slug], queryFn: () => api.farmer(slug) }); const products = useQuery({ queryKey: ["products", "farmer", slug], queryFn: () => api.products() }); if (farmer.isLoading) return <StateView state="loading" />; if (!farmer.data) return <StateView state="error" />; const f = farmer.data; return <ScrollView contentContainerStyle={s.page}><View style={s.hero}><Image source={{ uri: f.photoUrl }} style={s.photo} /><Text style={s.name}>{f.displayName}</Text><Text style={s.location}>{f.primaryFarm?.name} · {f.primaryFarm?.district}</Text><View style={s.stats}><Chip>★ {f.ratingAvg}</Chip><Chip>{f.experienceYears} years farming</Chip></View></View><ScreenTitle title={t("story")} /><Text style={s.story}>{f.story}</Text><View style={s.farm}><Text style={s.farmName}>{f.primaryFarm?.name}</Text><Text style={s.location}>{f.primaryFarm?.acreage} acres · {f.primaryFarm?.farmingMethods}</Text></View><ScreenTitle title={t("products")} />{products.data?.map((p) => <View key={p.id} style={{ marginBottom: 14 }}><ProductCard product={p} wide /></View>)}</ScrollView>; }
const s = StyleSheet.create({ page: { padding: 18, gap: 14, paddingBottom: 40 }, hero: { alignItems: "center", paddingVertical: 20 }, photo: { width: 126, height: 126, borderRadius: 44, backgroundColor: colors.primarySoft }, name: { fontSize: 27, fontWeight: "900", color: colors.text, marginTop: 14 }, location: { color: colors.muted, marginTop: 5 }, stats: { flexDirection: "row", gap: 8, marginTop: 13 }, story: { color: colors.muted, fontSize: 16, lineHeight: 25 }, farm: { backgroundColor: colors.cream, borderRadius: radius.lg, padding: 18 }, farmName: { color: colors.text, fontSize: 18, fontWeight: "800" } });
