import { useMutation } from "@tanstack/react-query";
import { router } from "expo-router";
import { useState } from "react";
import { KeyboardAvoidingView, Platform, StyleSheet, Text, View } from "react-native";
import { useTranslation } from "react-i18next";
import { api } from "../src/api";
import { tokenStore } from "../src/auth/tokens";
import { Button, Icon, Input, ScreenTitle } from "../src/components/ui";
import { colors } from "../src/theme";
export default function Auth() { const { t } = useTranslation(); const [phone, setPhone] = useState(""); const [otp, setOtp] = useState(""); const [sent, setSent] = useState(false); const request = useMutation({ mutationFn: () => api.requestOtp(phone), onSuccess: () => setSent(true) }); const verify = useMutation({ mutationFn: () => api.verifyOtp(phone, otp), onSuccess: async (tokens) => { await tokenStore.set(tokens); router.back(); } }); return <KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={s.page}><View style={s.icon}><Icon name="phone-portrait-outline" size={35} color={colors.white} /></View><ScreenTitle title={sent ? t("otp") : "Welcome back"} subtitle={sent ? `We sent a code to +91 ${phone}` : "Secure sign in with your mobile number"} />{!sent ? <Input accessibilityLabel={t("phone")} keyboardType="phone-pad" maxLength={10} value={phone} onChangeText={setPhone} placeholder={t("phone")} /> : <Input accessibilityLabel={t("otp")} keyboardType="number-pad" maxLength={6} value={otp} onChangeText={setOtp} placeholder="• • • • • •" />}<Button disabled={(!sent && phone.length !== 10) || (sent && otp.length !== 6) || request.isPending || verify.isPending} onPress={() => sent ? verify.mutate() : request.mutate()}>{sent ? t("verify") : t("sendOtp")}</Button>{(request.error || verify.error) && <Text accessibilityRole="alert" style={s.error}>{(request.error ?? verify.error)?.message}</Text>}<Text style={s.terms}>By continuing, you agree to our Terms and Privacy Policy.</Text></KeyboardAvoidingView>; }
const s = StyleSheet.create({ page: { flex: 1, padding: 24, justifyContent: "center", gap: 18 }, icon: { width: 68, height: 68, backgroundColor: colors.primary, borderRadius: 24, alignItems: "center", justifyContent: "center", marginBottom: 8 }, error: { color: colors.error, textAlign: "center" }, terms: { color: colors.muted, textAlign: "center", fontSize: 12, lineHeight: 18 } });
