import { router } from "expo-router";
import { useState } from "react";
import { ImageBackground, KeyboardAvoidingView, Platform, StyleSheet, Text, View } from "react-native";
import { useTranslation } from "react-i18next";
import { Button, Icon, Input } from "../src/components/ui";
import { useAppStore } from "../src/store/app";
import { colors, radius } from "../src/theme";
export default function Onboarding() { const { t } = useTranslation(); const [step, setStep] = useState(0); const [pincode, setPincode] = useState(""); const setLocation = useAppStore((s) => s.setLocation); const finish = () => { setLocation(pincode); router.replace("/(tabs)/home"); }; return <ImageBackground source={{ uri: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=1200" }} style={s.bg}><View style={s.overlay} /><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={s.content}><View style={s.brand}><Icon name="leaf" size={34} color={colors.white} /><Text style={s.logo}>{t("appName")}</Text><Text style={s.tag}>{t("tagline")}</Text></View><View style={s.card}>{step === 0 ? <><Text style={s.title}>{t("welcome")}</Text><Text style={s.body}>{t("onboardingBody")}</Text><Button onPress={() => setStep(1)}>{t("getStarted")}</Button></> : <><Text style={s.title}>{t("chooseLocation")}</Text><Text style={s.body}>We’ll show produce available near you.</Text><Input accessibilityLabel={t("pincode")} keyboardType="number-pad" maxLength={6} value={pincode} onChangeText={setPincode} placeholder={t("pincode")} /><Button disabled={pincode.length !== 6} onPress={finish}>{t("continue")}</Button></>}</View></KeyboardAvoidingView></ImageBackground>; }
const s = StyleSheet.create({ bg: { flex: 1 }, overlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(17,53,12,.48)" }, content: { flex: 1, padding: 24, justifyContent: "space-between", paddingTop: 100, paddingBottom: 42 }, brand: { alignItems: "center" }, logo: { color: colors.white, fontSize: 34, fontWeight: "900" }, tag: { color: colors.cream, marginTop: 5 }, card: { backgroundColor: colors.white, borderRadius: 28, padding: 24, gap: 17 }, title: { color: colors.text, fontWeight: "900", fontSize: 27 }, body: { color: colors.muted, fontSize: 16, lineHeight: 24 } });
