import type { Address, Category, Farmer, Order, Product } from "./types";
const farmer = { farmerId: "f1", farmerName: "Lakshmi Reddy", farmerSlug: "lakshmi-reddy", experienceYears: 18, farmId: "farm1", farmName: "Green Roots Farm", farmSlug: "green-roots", village: "Shamirpet", district: "Medchal", state: "Telangana" };
const variant = (id: string, label: string, price: number) => ({ id, unit: "KG" as const, unitSize: 1, label, mrp: price + 20, sellingPrice: price, savings: 20, minOrderQty: 1, maxOrderQty: 8, availableQty: 30, inStock: true });
export const categories: Category[] = [
  { id: "c1", name: { en: "Vegetables", te: "కూరగాయలు" }, slug: "vegetables", icon: "leaf-outline", sortOrder: 1 },
  { id: "c2", name: { en: "Fruits", te: "పండ్లు" }, slug: "fruits", icon: "nutrition-outline", sortOrder: 2 },
  { id: "c3", name: { en: "Millets", te: "చిరుధాన్యాలు" }, slug: "millets", icon: "sparkles-outline", sortOrder: 3 },
  { id: "c4", name: { en: "Dairy", te: "పాల ఉత్పత్తులు" }, slug: "dairy", icon: "water-outline", sortOrder: 4 },
];
export const products: Product[] = [
  { id: "p1", name: { en: "Fresh Country Tomatoes", te: "తాజా నాటు టమాటాలు" }, slug: "country-tomatoes", description: { en: "Naturally grown, hand-picked this morning and delivered farm-fresh.", te: "సహజంగా పండించి, ఈ ఉదయం చేతితో కోసిన తాజా టమాటాలు." }, categorySlug: "vegetables", growingMethod: "NATURAL", organicCertified: false, harvestDate: "2026-06-12", ratingAvg: 4.8, ratingCount: 124, farmer, imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800", defaultVariant: variant("v1", "1 kg", 58), variants: [variant("v1", "1 kg", 58), variant("v2", "2 kg", 108)] },
  { id: "p2", name: { en: "Organic Spinach", te: "సేంద్రియ పాలకూర" }, slug: "organic-spinach", categorySlug: "vegetables", growingMethod: "ORGANIC", organicCertified: true, ratingAvg: 4.9, ratingCount: 86, farmer, imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=800", defaultVariant: { ...variant("v3", "2 bunches", 42), unit: "BUNCH" } },
  { id: "p3", name: { en: "Sweet Mangoes", te: "తీపి మామిడి పండ్లు" }, slug: "sweet-mangoes", categorySlug: "fruits", growingMethod: "NATURAL", organicCertified: false, ratingAvg: 4.7, ratingCount: 205, farmer, imageUrl: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=800", defaultVariant: variant("v4", "1 kg", 160) },
  { id: "p4", name: { en: "Foxtail Millet", te: "కొర్రలు" }, slug: "foxtail-millet", categorySlug: "millets", growingMethod: "ORGANIC", organicCertified: true, ratingAvg: 4.6, ratingCount: 59, farmer, imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800", defaultVariant: variant("v5", "1 kg", 125) },
];
export const farmers: Farmer[] = [{ id: "f1", displayName: "Lakshmi Reddy", slug: "lakshmi-reddy", story: "For 18 years, Lakshmi has nurtured soil with natural methods and saved indigenous seeds.", experienceYears: 18, ratingAvg: 4.9, ratingCount: 231, photoUrl: "https://images.unsplash.com/photo-1590682680695-43b964a3ae17?w=800", primaryFarm: { id: "farm1", name: "Green Roots Farm", slug: "green-roots", village: "Shamirpet", district: "Medchal", state: "Telangana", acreage: 7, farmingMethods: "Natural and regenerative" } }];
export const addresses: Address[] = [{ id: "a1", label: "Home", recipient: "Vijay Kumar", phone: "9876543210", line1: "12-4, Lake View Colony", city: "Hyderabad", state: "Telangana", pincode: "500081", isDefault: true }];
export const orders: Order[] = [{ id: "o1", number: "MR24061832", createdAt: "2026-06-18T10:30:00Z", status: "OUT_FOR_DELIVERY", total: 258, address: addresses[0]!, items: [{ id: "i1", variantId: "v1", productId: "p1", productName: products[0]!.name, productSlug: products[0]!.slug, imageUrl: products[0]!.imageUrl, variantLabel: "2 kg", farmerName: "Lakshmi Reddy", mrp: 128, sellingPrice: 108, qty: 1, lineTotal: 108, lineSavings: 20 }], timeline: ["PLACED", "CONFIRMED", "FARMER_ACCEPTED", "PACKING", "READY_FOR_DISPATCH", "OUT_FOR_DELIVERY", "DELIVERED"].map((status, i) => ({ status: status as Order["status"], complete: i < 7 })) }];
