import { router } from "expo-router";
import { Image, ScrollView, StyleSheet, Text, View } from "react-native";
import { useTranslation } from "react-i18next";
import { products } from "../../src/api/mock";
import { Button, Icon, ScreenTitle, StateView } from "../../src/components/ui";
import { useAppStore } from "../../src/store/app";
import { colors, radius } from "../../src/theme";
export default function Cart() { const { t, i18n } = useTranslation(); const locale = i18n.language === "te" ? "te" : "en"; const cart = useAppStore((s) => s.cart); const update = useAppStore((s) => s.updateCart); const items = products.filter((p) => cart[p.id]).map((p) => ({ p, qty: cart[p.id]! })); const subtotal = items.reduce((a, x) => a + x.p.defaultVariant.sellingPrice * x.qty, 0); return <ScrollView contentContainerStyle={s.page}><ScreenTitle title={t("cart")} subtitle={`${items.length} farm-fresh selections`} />{!items.length ? <StateView state="empty" message="Your basket is ready for something fresh." /> : <>{items.map(({ p, qty }) => <View key={p.id} style={s.item}><Image source={{ uri: p.imageUrl }} style={s.image} /><View style={{ flex: 1 }}><Text style={s.name}>{p.name[locale]}</Text><Text style={s.muted}>{p.defaultVariant.label} · {p.farmer.farmerName}</Text><Text style={s.price}>₹{p.defaultVariant.sellingPrice * qty}</Text></View><View style={s.stepper}><Button variant="ghost" onPress={() => update(p.id, qty - 1)}>−</Button><Text style={s.qty}>{qty}</Text><Button variant="ghost" onPress={() => update(p.id, qty + 1)}>+</Button></View></View>)}<View style={s.bill}><Row label={t("subtotal")} value={`₹${subtotal}`} /><Row label={t("delivery")} value={subtotal >= 299 ? "FREE" : "₹40"} /><View style={s.line} /><Row label={t("total")} value={`₹${subtotal + (subtotal >= 299 ? 0 : 40)}`} bold /></View><Button onPress={() => router.push("/checkout")}>{t("checkout")}</Button></>}</ScrollView>; }
function Row({ label, value, bold }: { label: string; value: string; bold?: boolean }) { return <View style={s.row}><Text style={[s.muted, bold && s.name]}>{label}</Text><Text style={[s.price, bold && { fontSize: 19 }]}>{value}</Text></View>; }
const s = StyleSheet.create({ page: { padding: 18, paddingTop: 56, gap: 16 }, item: { flexDirection: "row", padding: 12, gap: 12, borderRadius: radius.lg, backgroundColor: colors.white, alignItems: "center" }, image: { width: 76, height: 76, borderRadius: radius.md }, name: { fontWeight: "800", color: colors.text }, muted: { color: colors.muted, marginTop: 4 }, price: { fontWeight: "800", color: colors.text, marginTop: 5 }, stepper: { alignItems: "center", gap: 3 }, qty: { fontWeight: "800", color: colors.text }, bill: { backgroundColor: colors.cream, borderRadius: radius.lg, padding: 18, gap: 12 }, row: { flexDirection: "row", justifyContent: "space-between" }, line: { height: 1, backgroundColor: colors.border } });
