import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { FlatList, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useTranslation } from "react-i18next";
import { api } from "../../src/api";
import { ProductCard } from "../../src/components/ProductCard";
import { Chip, Icon, Input, ScreenTitle, StateView } from "../../src/components/ui";
import { colors } from "../../src/theme";
export default function Discover() { const { t, i18n } = useTranslation(); const locale = i18n.language === "te" ? "te" : "en"; const [q, setQ] = useState(""); const [category, setCategory] = useState(""); const cats = useQuery({ queryKey: ["categories"], queryFn: api.categories }); const result = useQuery({ queryKey: ["products", q, category], queryFn: () => api.products({ q, category }) }); return <View style={s.page}><ScreenTitle title={t("discover")} subtitle="Seasonal, local and honestly grown" /><View><Input value={q} onChangeText={setQ} placeholder={t("search")} accessibilityLabel={t("search")} /><View style={s.searchIcon}><Icon name="search-outline" color={colors.muted} /></View></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}><Pressable onPress={() => setCategory("")}><Chip active={!category}>All</Chip></Pressable>{cats.data?.map((c) => <Pressable key={c.id} onPress={() => setCategory(c.slug)}><Chip active={category === c.slug}>{c.name[locale]}</Chip></Pressable>)}</ScrollView><Text style={s.count}>{result.data?.length ?? 0} {t("results")}</Text>{result.isLoading ? <StateView state="loading" /> : result.isError ? <StateView state="error" onRetry={() => void result.refetch()} /> : !result.data?.length ? <StateView state="empty" message={t("noResults")} /> : <FlatList data={result.data} keyExtractor={(p) => p.id} numColumns={2} columnWrapperStyle={s.grid} contentContainerStyle={s.list} renderItem={({ item }) => <View style={s.item}><ProductCard product={item} wide /></View>} />}</View>; }
const s = StyleSheet.create({ page: { flex: 1, paddingHorizontal: 16, paddingTop: 56 }, searchIcon: { position: "absolute", right: 15, top: 15 }, filters: { gap: 9, paddingVertical: 15 }, count: { color: colors.muted, fontWeight: "700", marginBottom: 8 }, grid: { gap: 12 }, item: { flex: 1, maxWidth: "49%", marginBottom: 14 }, list: { paddingBottom: 95 } });
