import { useQuery } from "@tanstack/react-query";
import { router } from "expo-router";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useTranslation } from "react-i18next";
import { api } from "../../src/api";
import { ProductCard } from "../../src/components/ProductCard";
import { Icon, ScreenTitle, StateView } from "../../src/components/ui";
import { useAppStore } from "../../src/store/app";
import { colors, radius } from "../../src/theme";
export default function Home() { const { t, i18n } = useTranslation(); const locale = i18n.language === "te" ? "te" : "en"; const pincode = useAppStore((s) => s.pincode); const products = useQuery({ queryKey: ["products", "fresh"], queryFn: () => api.products({ section: "fresh" }) }); const cats = useQuery({ queryKey: ["categories"], queryFn: api.categories }); const farmers = useQuery({ queryKey: ["farmers"], queryFn: api.farmers }); return <ScrollView contentContainerStyle={s.page}><View style={s.header}><View><Text style={s.hello}>{t("hello")}</Text><Pressable onPress={() => router.push("/onboarding")} style={s.location}><Icon name="location" size={17} /><Text style={s.locationText}>{t("location")} · {pincode}</Text></Pressable></View><Pressable onPress={() => router.push("/notifications")} style={s.icon}><Icon name="notifications-outline" /></Pressable></View><Pressable onPress={() => router.push("/(tabs)/discover")} style={s.search}><Icon name="search-outline" color={colors.muted} /><Text style={s.placeholder}>{t("search")}</Text></Pressable><View style={s.hero}><View style={{ flex: 1 }}><Text style={s.heroTitle}>Good food starts with good soil.</Text><Text style={s.heroBody}>Fresh harvests from farmers near you.</Text></View><Icon name="leaf" size={54} color={colors.primary} /></View><ScreenTitle title={t("categories")} />{cats.isLoading ? <StateView state="loading" /> : <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.row}>{cats.data?.map((c) => <Pressable key={c.id} onPress={() => router.push({ pathname: "/category/[slug]", params: { slug: c.slug } })} style={s.category}><View style={s.catIcon}><Icon name={c.icon as never} /></View><Text style={s.catText}>{c.name[locale]}</Text></Pressable>)}</ScrollView>}<ScreenTitle title={t("freshToday")} subtitle="Harvested close to home" />{products.isLoading ? <StateView state="loading" /> : products.isError ? <StateView state="error" onRetry={() => void products.refetch()} /> : <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.row}>{products.data?.map((p) => <ProductCard key={p.id} product={p} />)}</ScrollView>}<ScreenTitle title={t("farmers")} />{farmers.data?.map((f) => <Pressable key={f.id} onPress={() => router.push(`/farmer/${f.slug}`)} style={s.farmer}><Image source={{ uri: f.photoUrl }} style={s.avatar} /><View style={{ flex: 1 }}><Text style={s.farmerName}>{f.displayName}</Text><Text style={s.muted}>{f.experienceYears} years · {f.primaryFarm?.district}</Text></View><Icon name="chevron-forward" /></Pressable>)}</ScrollView>; }
const s = StyleSheet.create({ page: { padding: 18, paddingTop: 56, gap: 18, paddingBottom: 40 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, hello: { fontSize: 25, fontWeight: "900", color: colors.text }, location: { flexDirection: "row", alignItems: "center", marginTop: 5 }, locationText: { color: colors.muted, fontWeight: "600" }, icon: { backgroundColor: colors.white, padding: 12, borderRadius: 16 }, search: { height: 52, flexDirection: "row", alignItems: "center", gap: 10, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white, paddingHorizontal: 15 }, placeholder: { color: colors.muted }, hero: { backgroundColor: colors.primarySoft, borderRadius: radius.lg, padding: 20, flexDirection: "row", alignItems: "center" }, heroTitle: { color: colors.primaryDark, fontSize: 20, fontWeight: "900", lineHeight: 26 }, heroBody: { color: colors.muted, marginTop: 7 }, row: { gap: 13, paddingBottom: 12 }, category: { alignItems: "center", width: 75, gap: 7 }, catIcon: { backgroundColor: colors.primarySoft, width: 60, height: 60, borderRadius: 22, alignItems: "center", justifyContent: "center" }, catText: { fontSize: 12, fontWeight: "700", color: colors.text, textAlign: "center" }, farmer: { flexDirection: "row", backgroundColor: colors.white, borderRadius: radius.lg, padding: 13, alignItems: "center", gap: 13 }, avatar: { width: 60, height: 60, borderRadius: 20 }, farmerName: { fontWeight: "800", color: colors.text, fontSize: 16 }, muted: { color: colors.muted, marginTop: 4 } });
