import { Image, Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { useTranslation } from "react-i18next";
import type { Product } from "../api";
import { useAppStore } from "../store/app";
import { colors, radius, shadow } from "../theme";
import { Chip, Icon } from "./ui";
export function ProductCard({ product, wide = false }: { product: Product; wide?: boolean }) { const { i18n, t } = useTranslation(); const locale = i18n.language === "te" ? "te" : "en"; const add = useAppStore((s) => s.addToCart); const favorites = useAppStore((s) => s.favorites); const toggle = useAppStore((s) => s.toggleFavorite); return <Pressable onPress={() => router.push(`/product/${product.slug}`)} style={[s.card, wide && { width: "100%" }]}><View><Image source={{ uri: product.imageUrl }} style={[s.image, wide && { width: "100%" }]} /><Pressable accessibilityLabel="Toggle favorite" hitSlop={10} onPress={(e) => { e.stopPropagation(); toggle(product.id); }} style={s.heart}><Icon name={favorites.includes(product.id) ? "heart" : "heart-outline"} size={19} color={favorites.includes(product.id) ? colors.clay : colors.text} /></Pressable></View><View style={s.body}><Chip>{product.organicCertified ? t("organic") : t("natural")}</Chip><Text numberOfLines={2} style={s.name}>{product.name[locale]}</Text><Text numberOfLines={1} style={s.farmer}>{t("by")} {product.farmer.farmerName}</Text><View style={s.row}><View><Text style={s.price}>₹{product.defaultVariant.sellingPrice}</Text><Text style={s.unit}>{product.defaultVariant.label}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={`${t("add")} ${product.name[locale]}`} onPress={(e) => { e.stopPropagation(); void add(product); }} style={s.add}><Icon name="add" color={colors.white} /></Pressable></View></View></Pressable>; }
const s = StyleSheet.create({ card: { width: 190, borderRadius: radius.lg, backgroundColor: colors.white, overflow: "hidden", ...shadow }, image: { width: 190, height: 140, backgroundColor: colors.primarySoft }, heart: { position: "absolute", right: 10, top: 10, backgroundColor: colors.white, borderRadius: 20, padding: 7 }, body: { padding: 13, gap: 8, alignItems: "flex-start" }, name: { fontWeight: "800", color: colors.text, fontSize: 16, minHeight: 39 }, farmer: { color: colors.muted, fontSize: 12 }, row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", width: "100%" }, price: { color: colors.text, fontWeight: "800", fontSize: 17 }, unit: { color: colors.muted, fontSize: 11 }, add: { backgroundColor: colors.primary, borderRadius: 13, padding: 7 } });
