import { Ionicons } from "@expo/vector-icons";
import type { ComponentProps, ReactNode } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View, type PressableProps, type TextInputProps } from "react-native";
import { useTranslation } from "react-i18next";
import { colors, radius } from "../theme";
export function ScreenTitle({ title, subtitle }: { title: string; subtitle?: string }) { return <View style={s.titleWrap}><Text accessibilityRole="header" style={s.title}>{title}</Text>{subtitle && <Text style={s.subtitle}>{subtitle}</Text>}</View>; }
export function Button({ children, variant = "primary", ...props }: PressableProps & { children: ReactNode; variant?: "primary" | "outline" | "ghost" }) { return <Pressable accessibilityRole="button" style={({ pressed }) => [s.button, s[variant], pressed && { opacity: .75 }]} {...props}><Text style={[s.buttonText, variant !== "primary" && { color: colors.primary }]}>{children}</Text></Pressable>; }
export function Input(props: TextInputProps) { return <TextInput placeholderTextColor={colors.muted} style={s.input} {...props} />; }
export function Icon({ name, size = 22, color = colors.primary }: { name: ComponentProps<typeof Ionicons>["name"]; size?: number; color?: string }) { return <Ionicons name={name} size={size} color={color} />; }
export function StateView({ state, message, onRetry }: { state: "loading" | "empty" | "error"; message?: string; onRetry?: () => void }) { const { t } = useTranslation(); return <View accessibilityRole="alert" style={s.state}>{state === "loading" ? <ActivityIndicator color={colors.primary} /> : <Icon name={state === "error" ? "cloud-offline-outline" : "leaf-outline"} size={38} />}<Text style={s.stateText}>{message ?? t(state)}</Text>{onRetry && <Button variant="outline" onPress={onRetry}>{t("retry")}</Button>}</View>; }
export function Chip({ children, active }: { children: ReactNode; active?: boolean }) { return <View style={[s.chip, active && s.chipActive]}><Text style={[s.chipText, active && { color: colors.white }]}>{children}</Text></View>; }
const s = StyleSheet.create({ titleWrap: { gap: 3, marginBottom: 16 }, title: { fontSize: 26, fontWeight: "800", color: colors.text, letterSpacing: -.5 }, subtitle: { color: colors.muted, fontSize: 14 }, button: { minHeight: 50, borderRadius: radius.md, alignItems: "center", justifyContent: "center", paddingHorizontal: 20 }, primary: { backgroundColor: colors.primary }, outline: { borderWidth: 1.5, borderColor: colors.primary, backgroundColor: colors.white }, ghost: { backgroundColor: colors.primarySoft }, buttonText: { color: colors.white, fontSize: 15, fontWeight: "700" }, input: { height: 52, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.white, paddingHorizontal: 16, color: colors.text, fontSize: 15 }, state: { alignItems: "center", justifyContent: "center", padding: 36, gap: 12, minHeight: 180 }, stateText: { color: colors.muted, textAlign: "center" }, chip: { borderRadius: radius.pill, backgroundColor: colors.primarySoft, paddingHorizontal: 13, paddingVertical: 8 }, chipActive: { backgroundColor: colors.primary }, chipText: { color: colors.primaryDark, fontWeight: "700", fontSize: 12 } });
