import { useQuery } from "@tanstack/react-query";
import { useLocalSearchParams } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { useTranslation } from "react-i18next";
import { api } from "../../src/api";
import { Icon, ScreenTitle, StateView } from "../../src/components/ui";
import { colors, radius } from "../../src/theme";
export default function OrderDetail() { const { id } = useLocalSearchParams<{ id: string }>(); const { t } = useTranslation(); const query = useQuery({ queryKey: ["order", id], queryFn: () => api.order(id) }); if (query.isLoading) return <StateView state="loading" />; if (!query.data) return <StateView state="error" />; const o = query.data; return <ScrollView contentContainerStyle={s.page}><ScreenTitle title={`#${o.number}`} subtitle={`${o.items.length} items · ₹${o.total}`} /><View style={s.banner}><Icon name="bicycle-outline" size={36} color={colors.white} /><View><Text style={s.bannerTitle}>{o.status.replaceAll("_", " ")}</Text><Text style={s.bannerText}>Your produce is on its way</Text></View></View><Text style={s.heading}>{t("orderStatus")}</Text><View style={s.timeline}>{o.timeline.map((event, i) => <View key={event.status} style={s.event}><View style={s.rail}><View style={[s.dot, event.complete && s.done]}>{event.complete && <Icon name="checkmark" size={14} color={colors.white} />}</View>{i < o.timeline.length - 1 && <View style={[s.line, event.complete && s.lineDone]} />}</View><View><Text style={[s.status, !event.complete && s.pending]}>{event.status.replaceAll("_", " ")}</Text>{event.at && <Text style={s.date}>{event.at}</Text>}</View></View>)}</View><Text style={s.heading}>{t("address")}</Text><View style={s.address}><Text style={s.status}>{o.address.recipient}</Text><Text style={s.date}>{o.address.line1}, {o.address.city}, {o.address.pincode}</Text></View></ScrollView>; }
const s = StyleSheet.create({ page: { padding: 18, gap: 16 }, banner: { backgroundColor: colors.primary, borderRadius: radius.lg, padding: 19, flexDirection: "row", gap: 14, alignItems: "center" }, bannerTitle: { color: colors.white, fontWeight: "900", fontSize: 17 }, bannerText: { color: colors.primarySoft, marginTop: 3 }, heading: { fontSize: 18, fontWeight: "900", color: colors.text, marginTop: 4 }, timeline: { backgroundColor: colors.white, padding: 19, borderRadius: radius.lg }, event: { minHeight: 62, flexDirection: "row", gap: 13 }, rail: { alignItems: "center" }, dot: { width: 25, height: 25, borderRadius: 13, backgroundColor: colors.border, alignItems: "center", justifyContent: "center" }, done: { backgroundColor: colors.primary }, line: { width: 2, flex: 1, backgroundColor: colors.border }, lineDone: { backgroundColor: colors.primary }, status: { color: colors.text, fontWeight: "800", fontSize: 13 }, pending: { color: colors.muted }, date: { color: colors.muted, marginTop: 4, lineHeight: 20 }, address: { backgroundColor: colors.cream, padding: 17, borderRadius: radius.lg } });
